<?php
return array(
    1 => array(
        'slug' => 'tag',
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent',
            'MapasCulturais\Entities\Event',
            'MapasCulturais\Entities\Project',
            'MapasCulturais\Entities\Opportunity'
        )
    ),

    2 => array(
        'slug' => 'area',
        'required' => "Debe informar al menos un área de actuación",
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent'
        ),
        'restricted_terms' => array(
        		'Creación Artesanal - Alfarería',
			'Archivistica',
			'Arqueología',
			'Artes Visuales - Arquitectura',
			'Arte',
			'Artes Visuales - Arte digital',
			'Arte Moderno',
			'Arte Precolombino',
			'Artes Visuales - Artes del fuego',
			'Artes Escénicas',
			'Artes Visuales - Artes Gráficas',
			'Artes Literarias',
			'Artes Musicales',
			'Artes Visuales',
			'Bibliotecología',
			'Bienes Culturales',
			'Artes Musicales - Canto coral',
			'Creación Artesanal',
			'Creación Artesanal - Cerámica',
			'Creación Artesanal - Cerería',
			'Creación Artesanal - Cestería',
			'Cinematografía',
			'Artes Musicales - Composición',
			'Artes Literarias - Crónica',
			'Artes Literarias - Cuento',
			'Artes Escénicas - Danza clásica',
			'Artes Escénicas - Danza moderna y contemporánea',
			'Artes Escénicas - Danza Teatro',
			'Artes Escénicas - Danza Tradicional',
			'Artes Escénicas - Danza Urbana',
			'Deporte y Recreación',
			'Artes Visuales - Dibujo',
			'Artes Musicales - Dirección',
			'Artes Visuales - Diseño',
			'Artes Literarias - Dramaturgia',
			'Educación Cultural',
			'Artes Literarias - Ensayo',
			'Artes Visuales - Escultura',
			'Artes Visuales - Fotografía',
			'Historia',
			'Artes Visuales - Historieta',
			'Artes Visuales - Instalaciones',
			'Creación Artesanal - Jarcia',
			'Creación Artesanal - Jícaras(guacales)',
			'Gestión Cultural',
			'Lingüística',
			'Manifestaciones culturales vivas',
			'Memoria Histórica',
			'Artes Escénicas - Mimo y Pantomima',
			'Artes Literarias - Narrativa',
			'Artes Visuales - Net-Art',
			'Artes Literarias - Novela',
			'Artes Musicales - Opera',
			'Creación Artesanal - Orfebrería',
			'Artes Musicales - Orquesta',
			'Paisaje Cultural',
			'Paisaje Natural',
			'Artes Escénicas - Performance',
			'Artes Visuales - Pintura',
			'Artes Literarias - Poesía',
			'Creación Artesanal - Productos de jade',
			'Creación Artesanal - Productos de palma',
			'Creación Artesanal - Productos metálicos',
			'Artes Escénicas - Representación escénica informal',
			'Artes Escénicas - Teatro alternativo ',
			'Artes Escénicas - Teatro callejero',
			'Artes Escénicas - Teatro de sala',
			'Artes Escénicas - Teatro de títeres',
			'Artes Escénicas - Teatro realista',
			'Artes Escénicas - Teatro surrealista',
			'Creación Artesanal - Textiles',
			'Creación Artesanal - Trabajos en cuero',
			'Creación Artesanal - Trabajos en madera',
			'Creación Artesanal - Vidrio soplado',
			'Gestion Cultural',
			'Promoción Cultural',
	                'Otro'
        )
    ),

    3 => array(
        'slug' => 'linguagem',
        'required' => "Debe informar al menos un tipo",
        'entities' => array(
            'MapasCulturais\Entities\Event'
        ),

        'restricted_terms' => array(
        	'Charla',
        	'Ciclo',
		'Cine Foro',
		'Coloquio',
        	'Convención',
        	'Desfile',
		'Día de Plaza',
        	'Encuentro',
        	'Espectáculo',
        	'Festival',
        	'Fiestas patronales',
        	'Concierto',
        	'Intervención Urbana',
        	'Jornada',
        	'Lanzamiento',
        	'Muestra y/o exposición',
        	'Panel',
        	'Ponencia',
		'Certamen',
        	'Presentación',
		'Reconocimiento',
        	'Reunión',
        	'Seminario',
		'Simposio',
        	'Taller',
        	'Visitas',
        	'Otros'
        )
    )
);
